version: "3.8"

services:
  server:
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: ./bin/server
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./server.env
    depends_on:
      - db
  db:
    image: "postgres"
    volumes:
      - postgres_database:/var/lib/postgresql/data/
    env_file:
      - ./db.env

volumes:
  postgres_database: